// Code generated by mockery v2.33.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// CalculatePacks provides a mock function with given fields: itemsOrdered
func (_m *Service) CalculatePacks(itemsOrdered int) map[int]int {
	ret := _m.Called(itemsOrdered)

	var r0 map[int]int
	if rf, ok := ret.Get(0).(func(int) map[int]int); ok {
		r0 = rf(itemsOrdered)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[int]int)
		}
	}

	return r0
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
